[project]
name = 'Decentralized-Manufacturing-Quality-Control'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.material-testing]
path = 'contracts/material-testing.clar'
clarity_version = 2
epoch = 2.5

[contracts.production-batch]
path = 'contracts/production-batch.clar'
clarity_version = 2
epoch = 2.5

[contracts.supplier-verification]
path = 'contracts/supplier-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
